//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbSinavEntityEntities : DbContext
    {
        public DbSinavEntityEntities()
            : base("name=DbSinavEntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Lesson> Tbl_Lesson { get; set; }
        public virtual DbSet<Tbl_Points> Tbl_Points { get; set; }
        public virtual DbSet<Tbl_Student> Tbl_Student { get; set; }
        public virtual DbSet<Tbl_Clubs> Tbl_Clubs { get; set; }
    
        public virtual ObjectResult<pointsList_Result> pointsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pointsList_Result>("pointsList");
        }
    }
}
